<h1 style="color:green" align='center'>Numpy tutorial: iterate numpy array using nditer</h1>

In [3]:
import numpy as np

In [4]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

<h3 style="color:purple">Using normal for loop iteration</h3>

In [5]:
for row in a:
    for cell in row:
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


<h3 style="color:purple">For loop with flatten</h3>

In [11]:
for cell in a.flatten():
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [30]:
# array dimension
print('dimension:', a.ndim) 
print('item size:', a.itemsize)
print('data type:', a.dtype)
print('size:', a.size)

dimension: 2
item size: 4
data type: int32
size: 12


In [32]:
a = np.array([[1,2],[3,4]], dtype=np.float64)
print('item size:', a.itemsize)
print('data type:', a.dtype)
print('shape:', a.shape)

item size: 8
data type: float64
shape: (2, 2)


In [28]:
np.zeros((3,4))
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [33]:
np.arange(1,5)

array([1, 2, 3, 4])

In [35]:
np.arange(1,5,2)

array([1, 3])

In [36]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [40]:
a = np.arange(1,7)
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [60]:
a= a.reshape(3,2)
a.min()
a.max()
a.std()
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [58]:
a.sum(axis=0)

array([ 9, 12])

In [59]:
a.sum(axis=1)

array([ 3,  7, 11])

In [61]:
a.sum(axis=1)

array([ 3,  7, 11])

In [63]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [65]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(a)
print(b)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [67]:
a+b

array([[ 6,  8],
       [10, 12]])

In [69]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [70]:
a.dot(b)

array([[19, 22],
       [43, 50]])